// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwingTradeIA.Api.Data;

#nullable disable

namespace SwingTradeIA.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628113412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwingTradeIA.Api.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("BollingerLower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BollingerUpper")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ma21")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ma9")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Macd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MacdSignal")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Rsi")
                        .HasColumnType("numeric");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("SwingTradeIA.Api.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3811),
                            Name = "Petrobras PN",
                            Sector = "Petróleo & Gás",
                            Ticker = "PETR4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3833),
                            Name = "Vale ON",
                            Sector = "Mineração",
                            Ticker = "VALE3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3838),
                            Name = "Itaú Unibanco PN",
                            Sector = "Financeiro",
                            Ticker = "ITUB4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3841),
                            Name = "Bradesco PN",
                            Sector = "Financeiro",
                            Ticker = "BBDC4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3847),
                            Name = "Ambev ON",
                            Sector = "Bebidas",
                            Ticker = "ABEV3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3849),
                            Name = "WEG ON",
                            Sector = "Industrial",
                            Ticker = "WEGE3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3863),
                            Name = "Localiza ON",
                            Sector = "Mobilidade",
                            Ticker = "RENT3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3866),
                            Name = "Magazine Luiza ON",
                            Sector = "Varejo",
                            Ticker = "MGLU3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3868),
                            Name = "Banco do Brasil ON",
                            Sector = "Financeiro",
                            Ticker = "BBAS3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3870),
                            Name = "Engie Brasil ON",
                            Sector = "Energia Elétrica",
                            Ticker = "EGIE3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3872),
                            Name = "Telefônica ON",
                            Sector = "Telecomunicações",
                            Ticker = "VIVT3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3874),
                            Name = "Suzano ON",
                            Sector = "Papel & Celulose",
                            Ticker = "SUZB3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3877),
                            Name = "Lojas Renner ON",
                            Sector = "Varejo",
                            Ticker = "LREN3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3879),
                            Name = "Hapvida ON",
                            Sector = "Saúde",
                            Ticker = "HAPV3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 6, 28, 11, 34, 11, 124, DateTimeKind.Utc).AddTicks(3884),
                            Name = "Raia Drogasil ON",
                            Sector = "Saúde",
                            Ticker = "RADL3"
                        });
                });

            modelBuilder.Entity("SwingTradeIA.Api.Models.Analysis", b =>
                {
                    b.HasOne("SwingTradeIA.Api.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
